"""empty message

<<<<<<<< HEAD:migrations/versions/46d09381822b_.py
Revision ID: 46d09381822b
Revises: 
Create Date: 2025-01-29 05:17:29.107124
========
Revision ID: 966084308d60
Revises: 
Create Date: 2025-01-29 15:55:25.298543
>>>>>>>> 4c11f5827c2fd2e0dd87bf2722028bc31a7cf30b:migrations/versions/966084308d60_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/46d09381822b_.py
revision = '46d09381822b'
========
revision = '966084308d60'
>>>>>>>> 4c11f5827c2fd2e0dd87bf2722028bc31a7cf30b:migrations/versions/966084308d60_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('membership', sa.String(length=20), nullable=False),
    sa.Column('es_mayor', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('advertising',
    sa.Column('id_advertising', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_advertising')
    )
    op.create_table('forum',
    sa.Column('id_forum', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_forum')
    )
    op.create_table('invoice',
    sa.Column('id_invoce', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_invoce')
    )
    op.create_table('comment',
    sa.Column('id_comment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=True),
    sa.Column('id_forum', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_forum'], ['forum.id_forum'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id_comment'], ),
    sa.PrimaryKeyConstraint('id_comment')
    )
    op.create_table('favorite',
    sa.Column('id_favorite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_forum', sa.Integer(), nullable=True),
    sa.Column('id_advertising', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_advertising'], ['advertising.id_advertising'], ),
    sa.ForeignKeyConstraint(['id_forum'], ['forum.id_forum'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorite')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('comment')
    op.drop_table('invoice')
    op.drop_table('forum')
    op.drop_table('advertising')
    op.drop_table('user')
    # ### end Alembic commands ###
